- hosts: localhost
  sudo: yes

  vars:
    http_port: 80
    domain: example.com

  tasks:

    - name: install packages
      apt: name={{ item }} update_cache=yes state=latest
      with_items:
        - apache2
        - git

    - name: enabled mod_rewrite
      apache2_module: name=rewrite state=present
      notify:
        - restart apache2

    - name: apache2 listen on port {{ http_port }}
      lineinfile: dest=/etc/apache2/ports.conf regexp="^Listen " line="Listen {{ http_port }}" state=present
      notify:
        - restart apache2
        
    - name: Removing
       file:
         path: /var/www/html
         state: absent
 
    - name: clone basic html template
      git: repo=https://github.com/markbgrdt/MCSwebsite.git dest=/var/www/html update=no

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
